mediapipe_settings:
  eye_ar_consec_frames: 18
  mouth_ar_thresh: 0.5
  mouth_ar_consec_frames: 20

yolo_settings:
  confidence_thresh: 0.8
  score_thresh: 20 
  score_increment: 2
  score_decrement: 1

head_pose_settings:
  top_head_deviation_thresh: 25 
  pitch_deviation_thresh: 15
  roll_deviation_thresh: 18 
  y_deviation_thresh: 25 
  angle_thresh: 15
  yaw_thresh: 25
  consec_frames: 15 

  pitch_down_thresh: 15 
  pitch_up_thresh: -15   
  roll_thresh: 18

calibration_settings:
  calibration_frames: 50
  ear_calibration_factor: 0.75

sound_settings:
  sound_path: 'sound/TrinhAiCham.wav'