mediapipe_settings:
  eye_ar_consec_frames: 20
  mouth_ar_thresh: 0.6
  mouth_ar_consec_frames: 20

head_pose_settings:
  y_deviation_ratio_thresh: 0.3 # Ty le lech y so voi chieu cao khung hinh
  angle_deviation_thresh: 20 # Ty le lech goc 
  score_thresh: 30 # Nguong diem cho tu the dau 
  score_increment: 1
  score_decrement: 1
  consec_frames: 20

yolo_settings:
  confidence_thresh: 0.7  
  score_thresh: 35 
  score_increment: 3
  score_decrement: 1

calibration_settings:
  calibration_frames: 30 # So luong khung hinh de hieu chinh
  ear_calibration_factor: 0.85 # He sá»‘ hieu chinh EAR

sound_settings:
  sound_path: 'sound/TrinhAiCham.wav'